divyanshudhruv/Minifolio

- index.html
- js/copyRight.js
- style.css
Added a Copy Right text as follows:
Copyright @ 2023 All Rights Reserved | Template Developed With By <> Divyanshu Dhruv
***The year 2023 get dynamically updated, so their no need to update it again and again every year manually***
##
The design is made responsive. Proof is given below:
> Footer Enhanced ( Copyright with Year added & Fully Responsive )

- README.md
- css/button.css
- index.html
- js/script.js
Issue Title: Back to Top Button 
Issue Number: #7 
Close #7 
This pull request enhances the functionality of the "Back to Top" button in the HTML document by adding smooth scrolling behavior and dynamic visibility based on the user's scroll position. Here are the key changes:
Improved the styling of the button for better user experience.
Added a smooth transition effect on hover to make the button more interactive.
Added a click event listener to the "Back to Top" button.
When clicked, the page now smoothly scrolls back to the top.
The button dynamically appears when the user has scrolled down more than 200 pixels and hides when they are near the top of the page.
These enhancements provide a smoother and more user-friendly experience for navigating the webpage. …
> Added Back To Top Button

- index.html
[Minifolio](https://github.com/vcavanna/Minifolio)
Wrote style edits for index.html. Most significant change is rewording the copy under "Hi, I'm a developer."
Take a look at the use of links too... Sketch now links to sketch.com, which is what I believe you were talking about.
Note: I'm asking to merge to main. I know this is against contribution guidelines, but I figured it was a small change and that this wouldn't be an issue. Let me know if I'm wrong.
Not sure.
https://github.com/divyanshudhruv/Minifolio/issues/5
Files Changed
index.html
> Fixed index.html typos

- index.html
**This reverts the commit #49 due to error in styling of about section.**
> Revert " #49 "

- css/button.css
- index.html
- js/script.js
Enhances the back to top button
> Fix back to top button

- css/style.css
- index.html
Enhance the footer section by changing the styles.
> Enhance footer section

- README.md
- css/button.css
- css/preloader.css
- css/style.css
- index.html
- js/preloader.js
New feature: Addition of basic animation
> Add page loading animation 

- README.md
- css/button.css
- css/style.css
- index.html
- js/script.js
🚧 Expect bugs and changes.
Added dark mode
> Add Dark Mode-1

- README.md
- css/button.css
- css/style.css
- index.html
- js/script.js
Reverts divyanshudhruv/Minifolio#66
> Revert "Add Dark Mode-1"

- css/button.css
Reverts divyanshudhruv/Minifolio#89
> Revert "Add 404 page style"

- 404.html
- css/404.css
- css/button.css
- css/style.css
- index.html
Added a services section to the portfolio page to showcase the different services offered.
- Added a new services section with brief descriptions of each service offered.
- Closes #51
[Minifolio](https://github.com/Kawaljeet-943/Minifolio)
- `index.html` - Added the HTML structure for the services section.
- `css/style.css` - Added styles for the newly created services section.
> Add services section

- 404.html
- css/404.css
- css/button.css
- css/style.css
- index.html
This enhancement adds a new services section to the portfolio.
Contributor: @Kawaljeet-943 
Closes: #51 , #53 , #54 , #98
> 🔥 Enhancement: Add services section

- css/style.css
- index.html
I have added a timeline for school, college, and master's with title, year, and description.
-Added pop-up animations.
-Added responsiveness.
closes #113
> Education Timeline

- css/style.css
Added extra styles for `.home .container a.button` and `.home .container a.button:hover` in `styles.css`
> Add extra styles for main button

- css/navbar.css
Color of nav bar changed to match the theme of the website.
> Change background color of nav bar

- css/style.css
- index.html
> Enhanced the footer UI

- index.html
**Education** category added to the nav bar and referenced to the "Education" section of the page.
> Add "Education" to the nav bar

- LICENSE
- css/style.css
- index.html
The form features fields for the user’s name, email, subject, and message.
##Key Enhancements:
--User-Friendly Layout: Simplified design for easy navigation and completion.
--Responsive Design: Optimized for accessibility on various devices, ensuring a great experience for all users.
--Modern Styling: Aesthetic improvements to match the overall look and feel of the portfolio, creating a more inviting atmosphere.
Closes #102
>  Added a new contact form.

- LICENSE
- css/style.css
- index.html
Centered the text and the description for the service cards.
Before:
After:
Kindly look into this PR @divyanshudhruv.
> centered text and description for services cards

- LICENSE
- css/style.css
- index.html
Centered the Click Me button on the screen for mobile users. 
Also centered the Education Title.
> Centered click me button and education title

- README.md
- css/button.css
- css/style.css
- index.html
- js/script.js
- Added social media icons with links to the home section and footer.
- Enhanced back-to-top button with smooth scroll and visibility improvements.
- Fixed alignment issues in the home section and footer for better layout.
- Add resume button for mobile and small devices only
> 🔥 Enhancement : Add social icons

- css/navbar.css
- css/style.css
- index.html
Added Footer Section in Site 
Fixes: #181
> Fixes: #181 Added Footer section in Site

- css/blogSection.css
- css/navbar.css
- index.html
- js/navbar.js
- js/script.js
1. Added file `navbar.js` which contains the JS functionality
2. Fixed errors with `GSAP` library by:
-  Moving static library imports to the top of `index.html`.
- Putting all `GSAP` funtionality inside the `DOMContentLoaded` event listener in `script.js`.
3. Fixed/changed navbar styles in `navbar.css`.
4. Moving the `nav` element inside `index.html`.
#hacktoberfest
> Add navbar funtionality & fix multiple errors.

- src/components/navbar/navbar.css
- src/components/navbar/navbar.tsx
> Add responsive navbar 
